# Generated by Django 4.1.1 on 2022-09-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="body",
            field=models.TextField(default="default"),
            preserve_default=False,
        ),
    ]
